version: '3.8'

services:
  feedback-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"  # gRPC server
    environment:
      - GRPC_PORT=9090
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=feedback_user
      - DB_PASSWORD=feedback_password
      - DB_NAME=feedback_db
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=feedback-bucket
      - MINIO_USE_SSL=false
    depends_on:
      - postgres
      - minio
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: feedback_db
      POSTGRES_USER: feedback_user
      POSTGRES_PASSWORD: feedback_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    restart: unless-stopped

  # Database migration service
  migrate:
    image: migrate/migrate
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://feedback_user:feedback_password@postgres:5432/feedback_db?sslmode=disable",
      "up"
    ]
    restart: "no"

volumes:
  postgres-data:
  minio-data: